dist: trusty
sudo: required

language: node_js

node_js:
  - "10.16.3"
  
deploy:
  provider: firebase
  
branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build
  - sonar-scanner
  - ng e2e

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change

addons:
  sonarcloud:
    organization: "joergsesterhenn-github"
  sauce_connect: true
