dist: trusty
sudo: required

language: node_js

node_js:
  - "8.9.0"
  
deploy:
  provider: firebase
  
branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
	
addons:
  sonarcloud:
    organization: "joergsesterhenn" # the key of the org you chose at step #3

script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
  